<img style="float: left; margin: 30px 15px 15px 15px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzQj91sOlkeDFkg5HDbjtR4QJYmLXkfMNig&usqp=CAU" width="400" height="500" /> 
    
    
### <font color='navy'> Simulación matemática. 

**Nombres:** Samuel Rodríguez Partida | Gustavo de Anda Madrigal

**Fecha:** 11 de septiembre del 2022.

**Expediente** : ic727594  | 742126 
    
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: https://github.com/Samuelrodriguezp

# Tarea 3: Clase 5

## Enunciado de tarea 


## 8. Tarea 

### 8.1. Otro problema de transporte

La empresa Carbones de oriente debe ingresar a la empresa un requerimiento mínimo diario de carbón de $5000$ kg de carbón de alto volátil, $4000$ kg de medio volátil y $3000$ kg de bajo volátil para su debido proceso y trasformación. 

La entrada de estos se da en la siguiente tabla (los valores corresponden a un viaje en kg): 

-|Alto volátil|Medio volátil|Bajo volátil
:----|----|----|----
Mina sur|80|70|65
Mina norte|60|50|40
Mina central|40|30|20

El costo del trasporte de un viaje de cada mina es de 2500 dólares, 1500 dólares y 900 dólares, respectivamente. ¿Cuántos viajes de cada mina se deben recibir a diario para suplir los requerimientos mínimos y generar el menor costo de transporte? 

Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Cantidad de viajes de la mina sur  
+ $x_2:$ Cantidad de viajes de la mina norte  
+ $x_3:$ Cantidad de viajes de la mina central  


El objetivo consiste consiste en plantear el problema de programación lineal que permita satisfacer los requerimientos de la empresa Carbones de oriente y resolverlo con `linprog`.

### 8.2. 
Una empresa de muebles rústicos fabrica entre muchos otros productos cinco tipos de sillas A, B, C, D Y E, las cuales se venden a precio de $1100$, $1300$, $1200$, $980$ y $1010$ pesos cada una y respectivamente. 

Las sillas pasan por cinco procesos: corte, ensamblado, lijado, pintado y sellado, para lo cual se dispone máximo de $17$, $11$, $15$, $12$ y $14$ horas respectivamente a la semana para dedicar a estas operaciones a estos productos.

Los requerimientos, en horas, para cada una de las sillas está dado en la siguiente tabla:

-|Corte|Ensamblado|Lijado|Pintado|Sellado
:----|----|----|----|----|----
Silla A|3|1|3|1|1
Silla B|2|3|2|2|3
Silla C|5|2|2|3|1
Silla D|2|4|1|1|2
Silla E|1|0|2|2|3

¿Cuántas sillas de cada tipo se deben fabricar para suplir los requerimientos de disponibiladas semanal y generar la mayor utilidad en ventas? 

Para simplificar la notación use las siguientes variables: 

+ $x_A:$ Cantidad de sillas tipo A 
+ $x_B:$ Cantidad de sillas tipo B 
+ $x_C:$ Cantidad de sillas tipo C 
+ $x_D:$ Cantidad de sillas tipo D  
+ $x_E:$ Cantidad de sillas tipo E


El objetivo consiste consiste en plantear el problemade programación lineal que permita satisfacer los requerimientos de la empresa empresa de muebles y resolverlo con `linprog`.


## Problema 1. Código de solución estudiante 1

In [7]:
# Código de solución estudiante 1
#importar paquetes 

import numpy as np
import scipy.optimize as opt

# Matrices y cotas
c = np.array([2500,1500,900])
b = np.array([-5000,-4000,-3000])
A = np.array([[-80,-60,-40],
             [-70,-50,-30],
             [-65,-40,-20]])
# Resolver
sol_viajes = opt.linprog(c,A,b,method='simplex')
# Mostrar resultado
sol_viajes

     con: array([], dtype=float64)
     fun: 119999.99999999999
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([ 0.00000000e+00, -4.54747351e-13,  0.00000000e+00])
  status: 0
 success: True
       x: array([ 0., 50., 50.])

### Respuesta planteada en el ejercicio
 
**¿Cuántos viajes de cada mina se deben recibir a diario para suplir los requerimientos mínimos y generar el menor costo de transporte?**
- cero viajes de la mina sur para suplir los requerimientos mínimos y minimizar el costo.
- 50 viajes de la mina norte para suplir los requerimientos mínimos y minimizar el costo.
- 50 viajes de la mina central para suplir los requerimientos mínimos y minimizar el costo.

## Problema 1. Código de solución estudiante 2.

Fórmula de costo:

$$min_(x_1,x_2,x_3) 2,500x_1 + 1,500x_2 + 900x_3$$

Restricciones:

$$ 80x_1 + 60x_2 +40x_3 ≥ 5000$$
$$ 70x_1 + 50x_2 +30x_3 ≥ 4000$$
$$ 65x_1 + 40x_2 +20x_3 ≥ 3000$$

In [4]:
#Importo lo necesario
import numpy as np
import scipy.optimize as opt
#Establezco mis matrices

c= np.array([2500,1500,900])
A= np.array([[-80,-60,-40],
   [-70,-50,-30],
   [-65,-40,-20]])
b= np.array([-5000,-4000,-3000])

c,A,b

(array([2500, 1500,  900]),
 array([[-80, -60, -40],
        [-70, -50, -30],
        [-65, -40, -20]]),
 array([-5000, -4000, -3000]))

In [7]:
#Resuevlo con linprog
sol_mina2 = opt.linprog (c,A,b,method="simplex")
sol_mina2

     con: array([], dtype=float64)
     fun: 119999.99999999999
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([ 0.00000000e+00, -4.54747351e-13,  0.00000000e+00])
  status: 0
 success: True
       x: array([ 0., 50., 50.])

*Así nuestro procedimiento nos arroja

## Código de solución estudiante 2

In [8]:
# Objetivo: ¿Cuántas sillas de cada tipo se deben fabricar para suplir los requerimientos de disponibiladas semanal y generar la mayor utilidad en ventas? 

#¿Cuáles serán mis variables? #Número de sillas por cada tipo

import numpy as np
import scipy.optimize as opt

#Ya hecho mi análisis declararé mis matrices
#Mi matriz c será negativa p
c = -np.array([1100,1300,1200,980,1010])
b = np.array([17,11,15,12,14])
a = np.array([[3,2,5,2,1,],
             [1,3,2,4,0],
             [3,2,2,1,2],
             [1,2,3,1,2],
             [1,3,1,2,3]])
c , b, a 







(array([-1100, -1300, -1200,  -980, -1010]),
 array([17, 11, 15, 12, 14]),
 array([[3, 2, 5, 2, 1],
        [1, 3, 2, 4, 0],
        [3, 2, 2, 1, 2],
        [1, 2, 3, 1, 2],
        [1, 3, 1, 2, 3]]))

In [9]:

#Resolver
sol_sillas = opt.linprog(c,a,b,method="simplex")
#Mostrar resultado
sol_sillas

     con: array([], dtype=float64)
     fun: -7700.0
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([0.00000000e+00, 0.00000000e+00, 3.55271368e-15, 0.00000000e+00,
       0.00000000e+00])
  status: 0
 success: True
       x: array([2., 1., 1., 1., 2.])

### Respuesta planteada en el ejercicio.
 
 **Problema 1: Deben realizarse:**
 - 0 viajes a la mina sur
 - 50 viajes a la mina norte
 - 50 viajes a la mina central
 
**Problema 2: Deben producirse:**
 - 2 sillas tipo A
 - 1 silla tipo B
 - 1 silla tipo C
 - 1 silla tipo D
 - 2 sillas tipo E